# Generated by Django 3.1.3 on 2020-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=126)),
                ('subject', models.CharField(max_length=160)),
                ('comment', models.TextField(max_length=190)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
